### ISSUE TITLE
LD_PRELOAD can cause Python sanity test to fail

### ISSUE THREAD

**Issue by camaclean** [Fahey-McLay/xalt#18]
On Blue Waters, we have encountered a bug where xalt is unable to successfully execute Python due to a LD_PRELOAD being set which depends on libraries in LD_LIBRARY_PATH. Because xalt runs python with `LD_LIBRARY_PATH=$LD_LIB_PATH PATH=$PyPATH $MY_PYTHON` and LD_LIBRARY_PATH no longer contains the dependencies, the LD_PRELOAD causes the command to fail with a missing library error.

**Comment by rtmclay** [comment]
Does the python you are configuring XALT with also require LD_PRELOAD  and LD_LIBRARY_PATH?  In other words can you configure XALT where a python depends on LD_LIBRARY_PATH and an  empty LD_PRELOAD?

It is possible to remember the value of both LD_LIBRARY_PATH and LD_PRELOAD if really required.

**Comment by camaclean** [comment]
This isn't a problem with configuring XALT. This happens when a user tries to use XALT's aprun while using an LD_PRELOAD with dependencies in LD_LIBRARY_PATH. The python sanity check fails with "XALT: Error in python setup" and the missing dynamic linker dependency is the root of the problem which causes python to break. A user's environment variables can break XALT.

**Comment by rtmclay** [comment]
Thanks for the clarification, it helped in understanding the problem.  The fix was easy from there.  I modified ld.in and xalt_helper_function.sh to set LD_PRELOAD=  everywhere LD_LIBRARY_PATH is set.  You can pull version 1.1.2 and use it.  Or you can modify your copies of ld.in and xalt_helper_function.sh to match the changes in XALT 1.1.2.

Thanks very much for the bug report!   Please let us know if this fixes the problem you found.
