### ISSUE TITLE
xalt_run / job_id

### ISSUE THREAD

**Issue by jgphpc** [Fahey-McLay/xalt#20]
Hello,

Using xalt/076+directdb, i get empty `job_id` (unknown).
I believe the relevant code is from `site/xalt_site_pkg.py`

~~~
   93   elif (queueType == "SLURM"):
   94     num_nodes              = int(envT.get("SLURM_NNODES",0))
   95     coresPerNode           = int(envT.get("SLURM_CPUS_ON_NODE",0))
   96     userT['job_num_cores'] = num_nodes*coresPerNode
   97     userT['num_cores']     = num_nodes*coresPerNode
   98     sysT['num_nodes']      = "SLURM_JOB_NUM_NODES"   # or SLURM_NNODES
   99     sysT['job_id']         = "SLURM_JOB_ID"
~~~

I tried to add:
```
userT['job_id']        = int(envT.get("SLURM_JOBID",1))
```
but it does not solve my problem. Same issue with:
```
userT['job_id']        = os.environ.get("SLURM_JOBID","1")
```

Is sysT used in `run_to_db` or do you intentionally ignore job_id ?

Thanks in advance for your help.

**Comment by jgphpc** [comment]
It may be a consequence of https://github.com/Fahey-McLay/xalt/issues/19

**Comment by Fahey-McLay** [comment]
The change in #19 should have no effect on your problem.  Does this problem
occur every time? Does SLURM_JOB_ID have a value at the start of aprun?

Thanks
R.

On Mar 7, 2017 10:00 AM, "jgp" <notifications@github.com> wrote:

It may be a consequence of #19
<https://github.com/Fahey-McLay/xalt/issues/19>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Fahey-McLay/xalt/issues/20#issuecomment-284764418>, or mute
the thread

**Comment by jgphpc** [comment]
> Does this problem occur every time? 

yes, actually it never worked from day1. 

> Does SLURM_JOB_ID have a value at the start of aprun/srun ?

I can get it from a simple python script:

> srun.off -n1 -t1 ./env.py 

```
1
24
1066997
```

where env.py is:

```python
#!/usr/bin/env python

import os
print os.environ['SLURM_NNODES']
print os.environ['SLURM_CPUS_ON_NODE']
print os.environ['SLURM_JOB_ID']
```

but not in xalt. 
Would it help if i give you access to daint ?

**Comment by rtmclay** [comment]
Sure, I'll be happy to look at the problem on daint.  Let me know if you need me to do anything.
You can use my TACC email address if that will help.

**Comment by victorusu** [comment]
This was solved by adding `re.compile(r'^SLURM\S*'),` to the `tobeKeptKeyA` list that is described inside the issue #19 and adding `userT['job_id'] = int(envT.get("SLURM_JOBID",0)) ` to `site/xalt_site_pkg.py`.
